/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ThemeRouteImport } from './routes/theme'
import { Route as authCallbackRouteImport } from './routes/(auth)/callback'
import { Route as authSessionErrorRouteImport } from './routes/(auth)/session-error'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as ApiThemeRouteImport } from './routes/api/theme'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthStartRouteImport } from './routes/api/auth/start'
import { Route as ApiAuthEmailStartRouteImport } from './routes/api/auth/email/start'
import { Route as ApiAuthEmailVerifyRouteImport } from './routes/api/auth/email/verify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemeRoute = ThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const authCallbackRoute = authCallbackRouteImport.update({
  id: '/(auth)/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const authSessionErrorRoute = authSessionErrorRouteImport.update({
  id: '/(auth)/session-error',
  path: '/session-error',
  getParentRoute: () => rootRouteImport,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiThemeRoute = ApiThemeRouteImport.update({
  id: '/api/theme',
  path: '/api/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthStartRoute = ApiAuthStartRouteImport.update({
  id: '/api/auth/start',
  path: '/api/auth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEmailStartRoute = ApiAuthEmailStartRouteImport.update({
  id: '/api/auth/email/start',
  path: '/api/auth/email/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthEmailVerifyRoute = ApiAuthEmailVerifyRouteImport.update({
  id: '/api/auth/email/verify',
  path: '/api/auth/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/theme': typeof ThemeRoute
  '/callback': typeof authCallbackRoute
  '/session-error': typeof authSessionErrorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/api/theme': typeof ApiThemeRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/auth/email/start': typeof ApiAuthEmailStartRoute
  '/api/auth/email/verify': typeof ApiAuthEmailVerifyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/theme': typeof ThemeRoute
  '/callback': typeof authCallbackRoute
  '/session-error': typeof authSessionErrorRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/api/theme': typeof ApiThemeRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/auth/email/start': typeof ApiAuthEmailStartRoute
  '/api/auth/email/verify': typeof ApiAuthEmailVerifyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/theme': typeof ThemeRoute
  '/(auth)/callback': typeof authCallbackRoute
  '/(auth)/session-error': typeof authSessionErrorRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/api/theme': typeof ApiThemeRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/start': typeof ApiAuthStartRoute
  '/api/auth/email/start': typeof ApiAuthEmailStartRoute
  '/api/auth/email/verify': typeof ApiAuthEmailVerifyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/theme'
    | '/callback'
    | '/session-error'
    | '/verify-email'
    | '/api/theme'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/auth/email/start'
    | '/api/auth/email/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/theme'
    | '/callback'
    | '/session-error'
    | '/verify-email'
    | '/api/theme'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/auth/email/start'
    | '/api/auth/email/verify'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/theme'
    | '/(auth)/callback'
    | '/(auth)/session-error'
    | '/(auth)/verify-email'
    | '/api/theme'
    | '/api/auth/signout'
    | '/api/auth/start'
    | '/api/auth/email/start'
    | '/api/auth/email/verify'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ThemeRoute: typeof ThemeRoute
  authCallbackRoute: typeof authCallbackRoute
  authSessionErrorRoute: typeof authSessionErrorRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  ApiThemeRoute: typeof ApiThemeRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthStartRoute: typeof ApiAuthStartRoute
  ApiAuthEmailStartRoute: typeof ApiAuthEmailStartRoute
  ApiAuthEmailVerifyRoute: typeof ApiAuthEmailVerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theme': {
      id: '/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof ThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/callback': {
      id: '/(auth)/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof authCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/session-error': {
      id: '/(auth)/session-error'
      path: '/session-error'
      fullPath: '/session-error'
      preLoaderRoute: typeof authSessionErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/theme': {
      id: '/api/theme'
      path: '/api/theme'
      fullPath: '/api/theme'
      preLoaderRoute: typeof ApiThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/start': {
      id: '/api/auth/start'
      path: '/api/auth/start'
      fullPath: '/api/auth/start'
      preLoaderRoute: typeof ApiAuthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/email/start': {
      id: '/api/auth/email/start'
      path: '/api/auth/email/start'
      fullPath: '/api/auth/email/start'
      preLoaderRoute: typeof ApiAuthEmailStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/email/verify': {
      id: '/api/auth/email/verify'
      path: '/api/auth/email/verify'
      fullPath: '/api/auth/email/verify'
      preLoaderRoute: typeof ApiAuthEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ThemeRoute: ThemeRoute,
  authCallbackRoute: authCallbackRoute,
  authSessionErrorRoute: authSessionErrorRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  ApiThemeRoute: ApiThemeRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthStartRoute: ApiAuthStartRoute,
  ApiAuthEmailStartRoute: ApiAuthEmailStartRoute,
  ApiAuthEmailVerifyRoute: ApiAuthEmailVerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
