// The typed Drizzle schema is generated, never written: migrations are applied to a scratch
// database with Atlas, and drizzle-kit introspects the result. `check` regenerates into a temporary
// directory and compares byte for byte, so a stale or hand-edited artifact fails.

import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { findPackageJSON } from "node:module";
import { tmpdir } from "node:os";
import { dirname, join, relative } from "node:path";

import { applyMigrations } from "./atlas.js";
import { withPostgres } from "./postgres.js";
import type { Env, PostgresOptions } from "./postgres.js";
import { MissingToolError, runTool } from "./tools.js";

const generatedHeader = `// @generated by db-tools drizzle-generate from the database the migrations produce.
// The SQL migrations own the schema. Hand edits are lost and must never become migrations.
//
// Policies in this file are NOT a faithful record. drizzle-kit pull drops the USING expression
// from SELECT policies, so a policy that restricts rows reads here as though it does not.
// rls-verify is the authority on row level security, because it tests behaviour.

`;

const missing =
  "drizzle-kit is not installed. Add it beside @littleorgans/db-tools: pnpm add -D drizzle-kit";

/** drizzle-kit is an optional peer: the project pins the version, so the artifact is stable. */
export function drizzleKitBin(): string {
  // findPackageJSON, because drizzle-kit's exports hide both its manifest and its bin.
  const manifest = findPackageJSON("drizzle-kit", import.meta.url);
  if (manifest === undefined) throw new MissingToolError(missing);
  const parsed: unknown = JSON.parse(readFileSync(manifest, "utf8"));
  const bin =
    typeof parsed === "object" && parsed !== null && "bin" in parsed ? parsed.bin : undefined;
  const path =
    typeof bin === "object" && bin !== null && "drizzle-kit" in bin
      ? bin["drizzle-kit"]
      : undefined;
  if (typeof path !== "string")
    throw new MissingToolError(`${manifest} declares no drizzle-kit bin`);
  return join(dirname(manifest), path);
}

function listFiles(directory: string, root = directory): string[] {
  if (!existsSync(directory)) return [];
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? listFiles(path, root) : [relative(root, path)];
  });
}

function directoriesMatch(left: string, right: string): boolean {
  const leftFiles = listFiles(left).toSorted();
  const rightFiles = listFiles(right).toSorted();
  return (
    leftFiles.length === rightFiles.length &&
    leftFiles.every(
      (path, index) =>
        path === rightFiles[index] &&
        readFileSync(join(left, path)).equals(readFileSync(join(right, path))),
    )
  );
}

export interface DrizzleOptions {
  /** Migration directory applied with Atlas. */
  readonly migrations: string;
  /** The committed artifact directory. */
  readonly out: string;
  readonly postgres: PostgresOptions;
}

// drizzle-kit pull also writes a SQL snapshot, a journal and relations; only the schema is kept.
async function generateInto(
  destination: string,
  options: DrizzleOptions,
  env: Env | undefined,
): Promise<void> {
  const bin = drizzleKitBin();
  await withPostgres(
    "drizzle",
    (databaseUrl) => {
      applyMigrations(databaseUrl, options.migrations, env);
      runTool(
        process.execPath,
        [bin, "pull", "--dialect", "postgresql", "--url", databaseUrl, "--out", destination],
        { env, missing },
      );
    },
    options.postgres,
  );
  const schema = join(destination, "schema.ts");
  if (!existsSync(schema)) throw new Error("drizzle-kit did not generate a TypeScript schema.");
  const contents = generatedHeader + readFileSync(schema, "utf8");
  rmSync(destination, { recursive: true, force: true });
  mkdirSync(destination, { recursive: true });
  writeFileSync(schema, contents);
}

async function withCandidate<T>(
  options: DrizzleOptions,
  use: (candidate: string) => T,
): Promise<T> {
  const candidate = mkdtempSync(join(tmpdir(), "drizzle-candidate-"));
  try {
    await generateInto(candidate, options, options.postgres.env);
    return use(candidate);
  } finally {
    rmSync(candidate, { recursive: true, force: true });
  }
}

/** Replaces the artifact directory with a freshly generated schema. */
export async function generateDrizzleSchema(options: DrizzleOptions): Promise<void> {
  await withCandidate(options, (candidate) => {
    rmSync(options.out, { recursive: true, force: true });
    mkdirSync(options.out, { recursive: true });
    cpSync(candidate, options.out, { recursive: true });
  });
}

/** Whether the artifact directory is exactly what the migrations generate now. */
export function drizzleSchemaIsCurrent(options: DrizzleOptions): Promise<boolean> {
  return withCandidate(options, (candidate) => directoriesMatch(candidate, options.out));
}
