import { execFileSync, spawnSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";

const artifactDirectory = "drizzle/_generated";
const generatedHeader = `// @generated by root:drizzle-generate from the database produced by Atlas migrations.
// Atlas SQL owns the schema. Hand edits are lost and must never become migrations.

`;

function run(command, args, capture = false) {
  return execFileSync(command, args, {
    encoding: "utf8",
    stdio: capture ? ["ignore", "pipe", "pipe"] : "inherit",
  });
}

function dockerIsAvailable() {
  return spawnSync("docker", ["info"], { stdio: "ignore" }).status === 0;
}

function waitForPostgres(container) {
  const deadline = Date.now() + 15_000;
  while (Date.now() < deadline) {
    const ready = spawnSync(
      "docker",
      [
        "exec",
        container,
        "pg_isready",
        "--host",
        "127.0.0.1",
        "--timeout",
        "1",
        "--username",
        "postgres",
        "--dbname",
        "app",
      ],
      { stdio: "ignore" },
    );
    if (ready.status === 0) return;
    const remaining = deadline - Date.now();
    if (remaining > 0) {
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, Math.min(250, remaining));
    }
  }
  throw new Error("Postgres did not accept TCP connections within 15 seconds.");
}

function listFiles(directory, root = directory) {
  if (!existsSync(directory)) return [];
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? listFiles(path, root) : [relative(root, path)];
  });
}

function keepSchemaArtifact(directory) {
  const schema = join(directory, "schema.ts");
  if (!existsSync(schema)) throw new Error("Drizzle did not generate a TypeScript schema.");
  const contents = generatedHeader + readFileSync(schema, "utf8");
  rmSync(directory, { recursive: true, force: true });
  mkdirSync(directory, { recursive: true });
  writeFileSync(schema, contents);
}

function directoriesMatch(left, right) {
  const leftFiles = listFiles(left).toSorted();
  const rightFiles = listFiles(right).toSorted();
  return (
    leftFiles.length === rightFiles.length &&
    leftFiles.every(
      (path, index) =>
        path === rightFiles[index] &&
        readFileSync(join(left, path)).equals(readFileSync(join(right, path))),
    )
  );
}

function generateInto(destination) {
  const container = `lilo-drizzle-${process.pid}`;
  try {
    run("docker", [
      "run",
      "--detach",
      "--rm",
      "--name",
      container,
      "--env",
      "POSTGRES_PASSWORD=postgres",
      "--env",
      "POSTGRES_DB=app",
      "--publish",
      "127.0.0.1::5432",
      "postgres:17-alpine",
    ]);
    waitForPostgres(container);
    const portOutput = run("docker", ["port", container, "5432/tcp"], true).trim();
    const port = portOutput.match(/:(\d+)$/)?.[1];
    if (port === undefined) throw new Error(`Could not parse the Postgres port: ${portOutput}`);
    const databaseUrl = `postgres://postgres:postgres@127.0.0.1:${port}/app?sslmode=disable`;
    run("atlas", ["migrate", "apply", "--dir", "file://migrations", "--url", databaseUrl]);
    run("pnpm", [
      "exec",
      "drizzle-kit",
      "pull",
      "--dialect",
      "postgresql",
      "--url",
      databaseUrl,
      "--out",
      destination,
    ]);
    keepSchemaArtifact(destination);
  } finally {
    spawnSync("docker", ["rm", "--force", container], { stdio: "ignore" });
  }
}

const mode = process.argv[2];
if (mode !== "generate" && mode !== "check") {
  throw new Error("Usage: node scripts/drizzle-schema.mjs <generate|check>");
}

if (mode === "check" && !process.env.CI && !dockerIsAvailable()) {
  process.stdout.write(
    "Drizzle schema check skipped locally: Docker is unavailable; CI will run it.\n",
  );
  process.exit(0);
}

const candidateDirectory = mkdtempSync(join(tmpdir(), "lilo-drizzle-candidate-"));
try {
  generateInto(candidateDirectory);
  if (mode === "generate") {
    rmSync(artifactDirectory, { recursive: true, force: true });
    mkdirSync(artifactDirectory, { recursive: true });
    cpSync(candidateDirectory, artifactDirectory, { recursive: true });
    process.stdout.write(`Generated Drizzle schema artifact at ${artifactDirectory}.\n`);
  } else if (!directoriesMatch(candidateDirectory, artifactDirectory)) {
    process.stderr.write(
      "Drizzle schema artifact is stale or was edited by hand. " +
        "Files under drizzle/_generated are generated and hand edits are lost. " +
        "Regenerate with: moon run root:drizzle-generate\n",
    );
    process.exitCode = 1;
  } else {
    process.stdout.write("Drizzle schema artifact matches the applied Atlas migrations.\n");
  }
} finally {
  rmSync(candidateDirectory, { recursive: true, force: true });
}
