import {
  cpSync,
  existsSync,
  mkdtempSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";

import {
  applyMigrations,
  dockerIsAvailable,
  run,
  withPostgres,
} from "./lib/postgres-container.mjs";

const artifactDirectory = "db/drizzle/_generated";
const generatedHeader = `// @generated by root:drizzle-generate from the database produced by Atlas migrations.
// Atlas SQL owns the schema. Hand edits are lost and must never become migrations.
//
// Policies in this file are NOT a faithful record. drizzle-kit pull drops the USING expression
// from SELECT policies, so a policy that restricts rows reads here as though it does not.
// root:rls-verify is the authority on row level security, because it tests behaviour.

`;

function listFiles(directory, root = directory) {
  if (!existsSync(directory)) return [];
  return readdirSync(directory, { withFileTypes: true }).flatMap((entry) => {
    const path = join(directory, entry.name);
    return entry.isDirectory() ? listFiles(path, root) : [relative(root, path)];
  });
}

function keepSchemaArtifact(directory) {
  const schema = join(directory, "schema.ts");
  if (!existsSync(schema)) throw new Error("Drizzle did not generate a TypeScript schema.");
  const contents = generatedHeader + readFileSync(schema, "utf8");
  rmSync(directory, { recursive: true, force: true });
  mkdirSync(directory, { recursive: true });
  writeFileSync(schema, contents);
}

function directoriesMatch(left, right) {
  const leftFiles = listFiles(left).toSorted();
  const rightFiles = listFiles(right).toSorted();
  return (
    leftFiles.length === rightFiles.length &&
    leftFiles.every(
      (path, index) =>
        path === rightFiles[index] &&
        readFileSync(join(left, path)).equals(readFileSync(join(right, path))),
    )
  );
}

function generateInto(destination) {
  return withPostgres((databaseUrl) => {
    applyMigrations(databaseUrl);
    run("pnpm", [
      "exec",
      "drizzle-kit",
      "pull",
      "--dialect",
      "postgresql",
      "--url",
      databaseUrl,
      "--out",
      destination,
    ]);
    keepSchemaArtifact(destination);
  });
}

const mode = process.argv[2];
if (mode !== "generate" && mode !== "check") {
  throw new Error("Usage: node scripts/drizzle-schema.mjs <generate|check>");
}

if (mode === "check" && !process.env.CI && !dockerIsAvailable()) {
  process.stdout.write(
    "Drizzle schema check skipped locally: Docker is unavailable; CI will run it.\n",
  );
  process.exit(0);
}

const candidateDirectory = mkdtempSync(join(tmpdir(), "drizzle-candidate-"));
try {
  await generateInto(candidateDirectory);
  if (mode === "generate") {
    rmSync(artifactDirectory, { recursive: true, force: true });
    mkdirSync(artifactDirectory, { recursive: true });
    cpSync(candidateDirectory, artifactDirectory, { recursive: true });
    process.stdout.write(`Generated Drizzle schema artifact at ${artifactDirectory}.\n`);
  } else if (!directoriesMatch(candidateDirectory, artifactDirectory)) {
    process.stderr.write(
      "Drizzle schema artifact is stale or was edited by hand. " +
        `Files under ${artifactDirectory} are generated and hand edits are lost. ` +
        "Regenerate with: moon run root:drizzle-generate\n",
    );
    process.exitCode = 1;
  } else {
    process.stdout.write("Drizzle schema artifact matches the applied Atlas migrations.\n");
  }
} finally {
  rmSync(candidateDirectory, { recursive: true, force: true });
}
