// Generates packages/theme/css/themes.css from the typed themes, or verifies it has not drifted.
// Same shape as scripts/drizzle-schema.mjs: `generate` rewrites the committed artifact, `check`
// fails CI when the artifact disagrees with its source. The import is the built package, which is
// why the moon tasks depend on theme:build.
import { readFileSync, writeFileSync } from "node:fs";

import { DEFAULT_THEME_NAME, renderThemesCss, themes } from "../packages/theme/dist/index.js";

const artifact = "packages/theme/css/themes.css";
const header = `/* @generated by root:theme-generate from packages/theme/src. Do not edit. */\n\n`;
const expected = header + renderThemesCss(themes, { defaultTheme: DEFAULT_THEME_NAME });

const mode = process.argv[2];
if (mode !== "generate" && mode !== "check") {
  console.error("Usage: node scripts/theme-css.mjs <generate|check>");
  process.exit(2);
}

if (mode === "generate") {
  writeFileSync(artifact, expected);
  console.error(`Wrote ${artifact}.`);
} else {
  let committed = null;
  try {
    committed = readFileSync(artifact, "utf8");
  } catch {
    // Missing is drift too; the message below says how to fix both.
  }
  if (committed !== expected) {
    console.error(
      `${artifact} does not match packages/theme/src. Run: moon run root:theme-generate`,
    );
    process.exit(1);
  }
  console.error(`${artifact} matches packages/theme/src.`);
}
