// @generated by root:drizzle-generate from the database produced by Atlas migrations.
// Atlas SQL owns the schema. Hand edits are lost and must never become migrations.
//
// Policies in this file are NOT a faithful record. drizzle-kit pull drops the USING expression
// from SELECT policies, so a policy that restricts rows reads here as though it does not.
// root:rls-verify is the authority on row level security, because it tests behaviour.

import { pgTable, unique, pgPolicy, uuid, text, timestamp } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const accounts = pgTable("accounts", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	workosOrgId: text("workos_org_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("accounts_workos_org_id_key").on(table.workosOrgId),
	pgPolicy("accounts_insert", { as: "permissive", for: "insert", to: ["public"], withCheck: sql`(workos_org_id = app.current_org_id())`  }),
	pgPolicy("accounts_select", { as: "permissive", for: "select", to: ["public"] }),
]);

export const profiles = pgTable("profiles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	workosUserId: text("workos_user_id").notNull(),
	createdAt: timestamp("created_at", { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
}, (table) => [
	unique("profiles_workos_user_id_key").on(table.workosUserId),
	pgPolicy("profiles_update", { as: "permissive", for: "update", to: ["public"], using: sql`(workos_user_id = app.current_user_id())`, withCheck: sql`(workos_user_id = app.current_user_id())`  }),
	pgPolicy("profiles_insert", { as: "permissive", for: "insert", to: ["public"] }),
	pgPolicy("profiles_select", { as: "permissive", for: "select", to: ["public"] }),
]);
