// @generated by root:drizzle-generate from the database produced by Atlas migrations.
// Atlas SQL owns the schema. Hand edits are lost and must never become migrations.

import { pgTable, integer } from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"



export const exampleItems = pgTable("example_items", {
	id: integer().primaryKey().notNull(),
});
