name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: blob:none

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "24.19.0"
          cache: pnpm

      - uses: moonrepo/setup-toolchain@v0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: moon ci
        run: moon ci
        env:
          MOON_BASE: ${{ github.event.pull_request.base.sha || github.event.before }}
          MOON_HEAD: ${{ github.event.pull_request.head.sha || github.sha }}
